"""Initial schema

Revision ID: 9935a671dec6
Revises: 
Create Date: 2026-05-03 01:50:40.524127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9935a671dec6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('abn', sa.String(), nullable=True),
    sa.Column('acn', sa.String(), nullable=True),
    sa.Column('entity_status', sa.String(), nullable=True),
    sa.Column('gst_status', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_abn', 'companies', ['abn'], unique=False)
    op.create_index('idx_company_name', 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_abn'), 'companies', ['abn'], unique=True)
    op.create_index(op.f('ix_companies_acn'), 'companies', ['acn'], unique=True)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('reputation_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_id'), 'directors', ['id'], unique=False)
    op.create_index(op.f('ix_directors_normalized_name'), 'directors', ['normalized_name'], unique=False)
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_runs_id'), 'scraper_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_runs_scraper_name'), 'scraper_runs', ['scraper_name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('is_read', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_company_id'), 'alerts', ['company_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('company_directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_directors_company_id'), 'company_directors', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_directors_director_id'), 'company_directors', ['director_id'], unique=False)
    op.create_index(op.f('ix_company_directors_id'), 'company_directors', ['id'], unique=False)
    op.create_table('distress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_distress_event_date', 'distress_events', ['event_date'], unique=False)
    op.create_index('idx_distress_event_severity', 'distress_events', ['severity'], unique=False)
    op.create_index('idx_distress_event_type', 'distress_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_distress_events_company_id'), 'distress_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_distress_events_event_date'), 'distress_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_distress_events_event_type'), 'distress_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_distress_events_id'), 'distress_events', ['id'], unique=False)
    op.create_index(op.f('ix_distress_events_severity'), 'distress_events', ['severity'], unique=False)
    op.create_table('distress_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distress_scores_company_id'), 'distress_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_distress_scores_id'), 'distress_scores', ['id'], unique=False)
    op.create_table('intelligence_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('feed_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_feed_id'), 'intelligence_feed', ['id'], unique=False)
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('change_delta', sa.Integer(), nullable=True),
    sa.Column('momentum', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_score_history_company_date', 'score_history', ['company_id', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_score_history_calculated_at'), 'score_history', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_score_history_company_id'), 'score_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_score_history_id'), 'score_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_history_id'), table_name='score_history')
    op.drop_index(op.f('ix_score_history_company_id'), table_name='score_history')
    op.drop_index(op.f('ix_score_history_calculated_at'), table_name='score_history')
    op.drop_index('idx_score_history_company_date', table_name='score_history')
    op.drop_table('score_history')
    op.drop_index(op.f('ix_intelligence_feed_id'), table_name='intelligence_feed')
    op.drop_table('intelligence_feed')
    op.drop_index(op.f('ix_distress_scores_id'), table_name='distress_scores')
    op.drop_index(op.f('ix_distress_scores_company_id'), table_name='distress_scores')
    op.drop_table('distress_scores')
    op.drop_index(op.f('ix_distress_events_severity'), table_name='distress_events')
    op.drop_index(op.f('ix_distress_events_id'), table_name='distress_events')
    op.drop_index(op.f('ix_distress_events_event_type'), table_name='distress_events')
    op.drop_index(op.f('ix_distress_events_event_date'), table_name='distress_events')
    op.drop_index(op.f('ix_distress_events_company_id'), table_name='distress_events')
    op.drop_index('idx_distress_event_type', table_name='distress_events')
    op.drop_index('idx_distress_event_severity', table_name='distress_events')
    op.drop_index('idx_distress_event_date', table_name='distress_events')
    op.drop_table('distress_events')
    op.drop_index(op.f('ix_company_directors_id'), table_name='company_directors')
    op.drop_index(op.f('ix_company_directors_director_id'), table_name='company_directors')
    op.drop_index(op.f('ix_company_directors_company_id'), table_name='company_directors')
    op.drop_table('company_directors')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_company_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_scraper_runs_scraper_name'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_id'), table_name='scraper_runs')
    op.drop_table('scraper_runs')
    op.drop_index(op.f('ix_directors_normalized_name'), table_name='directors')
    op.drop_index(op.f('ix_directors_id'), table_name='directors')
    op.drop_table('directors')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_acn'), table_name='companies')
    op.drop_index(op.f('ix_companies_abn'), table_name='companies')
    op.drop_index('idx_company_name', table_name='companies')
    op.drop_index('idx_company_abn', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
