from enum import Enum

class EventType(str, Enum):
    # HIGH PRIORITY
    ATO_WINDING_UP = "ATO_WINDING_UP"
    FEDERAL_COURT_ACTION = "FEDERAL_COURT_ACTION"
    PPSR_SPIKE = "PPSR_SPIKE"
    DIRECTOR_FAILED_ENTITY_LINK = "DIRECTOR_FAILED_ENTITY_LINK"

    # MEDIUM PRIORITY
    LATE_FILING = "LATE_FILING"
    NEGATIVE_NEWS = "NEGATIVE_NEWS"
    DIRECTOR_RESIGNATION = "DIRECTOR_RESIGNATION"
    TAX_DEBT_SIGNAL = "TAX_DEBT_SIGNAL"

    # LOW PRIORITY
    OPERATIONAL_CHANGE = "OPERATIONAL_CHANGE"
    MEDIA_MENTION = "MEDIA_MENTION"

class Priority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
